ignore:
  - '**/*.gr.dart'
  - '**/*.g.dart'
  - '**/*.freezed.dart'
  - "**/*.mocks.dart"
  - '**/constants.dart'
  - '**/routes.dart'
  - '**/custom_theme.dart'
  - '**/assets_helper.dart'
  - '/android/'
  - '/ios/'
  - '/build/'